added colors in taiwind config and made changes required
chefinazia/baxter-cms pull request #4
Opened 2024-09-25 10:25 UTC by chefinazia

<img width="959" alt="image" src="https://github.com/user-attachments/assets/617207c4-21e6-48f6-a2ad-59685b03ff67">

2024-09-25 19:04 UTC, Deepak-Bulani requested changes

2024-09-25 19:04 UTC, Deepak-Bulani commented on src/App.jsx
> +      <div className="">
if class doesn't exist, remove className

2024-09-26 05:02 UTC, chefinazia commented on src/components/CalendarPatientsList.jsx
> +          <div className="grid-rows-2 gap-4">
replaced with div

2024-09-26 05:02 UTC, chefinazia commented on src/App.jsx
> +      <div className="">
removed

2024-09-26 05:02 UTC, chefinazia commented on src/components/CalendarPatientsList.jsx
> +          className="flex divide-x-3 m-auto max-w-fit px-4 justify-center align-middle bg-primary-secondaryTabColor none border border-primary-secondaryTabColorBorderColor center rounded-md font-seri
okay removed

2024-09-26 05:16 UTC, kanayan007 requested changes

2024-09-26 05:16 UTC, kanayan007 commented on src/components/CalendarPatientsList.jsx
>              </a>
Avoid using Anchor tag for achieving some functionality based on onClick. Anchor tag will be used for navigation and does a full page reload unless you use preventDefault(). So, for navigation also we should be using Link tag from react-router-dom

2024-09-26 11:20 UTC, merged